/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FreeClassRouteImport } from './routes/free-class'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CheckoutErrorRouteImport } from './routes/checkout.error'
import { Route as CheckoutCancelledRouteImport } from './routes/checkout.cancelled'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedDashboardSupportRouteImport } from './routes/_authenticated/dashboard.support'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated/dashboard.orders'
import { Route as AuthenticatedCheckoutCourseIdRouteImport } from './routes/_authenticated/checkout.$courseId'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as ApiPublicWebhooksUddoktapayRouteImport } from './routes/api/public/webhooks/uddoktapay'
import { Route as AuthenticatedDashboardCoursesIdRouteImport } from './routes/_authenticated/dashboard.courses.$id'
import { Route as AuthenticatedAdminCoursesIdEditRouteImport } from './routes/_authenticated/admin.courses.$id.edit'

const FreeClassRoute = FreeClassRouteImport.update({
  id: '/free-class',
  path: '/free-class',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutErrorRoute = CheckoutErrorRouteImport.update({
  id: '/checkout/error',
  path: '/checkout/error',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelledRoute = CheckoutCancelledRouteImport.update({
  id: '/checkout/cancelled',
  path: '/checkout/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDashboardSupportRoute =
  AuthenticatedDashboardSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedCheckoutCourseIdRoute =
  AuthenticatedCheckoutCourseIdRouteImport.update({
    id: '/checkout/$courseId',
    path: '/checkout/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicWebhooksUddoktapayRoute =
  ApiPublicWebhooksUddoktapayRouteImport.update({
    id: '/api/public/webhooks/uddoktapay',
    path: '/api/public/webhooks/uddoktapay',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardCoursesIdRoute =
  AuthenticatedDashboardCoursesIdRouteImport.update({
    id: '/courses/$id',
    path: '/courses/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminCoursesIdEditRoute =
  AuthenticatedAdminCoursesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/free-class': typeof FreeClassRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/error': typeof CheckoutErrorRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/checkout/$courseId': typeof AuthenticatedCheckoutCourseIdRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/courses/$id': typeof AuthenticatedDashboardCoursesIdRoute
  '/api/public/webhooks/uddoktapay': typeof ApiPublicWebhooksUddoktapayRoute
  '/admin/courses/$id/edit': typeof AuthenticatedAdminCoursesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/free-class': typeof FreeClassRoute
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/error': typeof CheckoutErrorRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/checkout/$courseId': typeof AuthenticatedCheckoutCourseIdRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/courses/$id': typeof AuthenticatedDashboardCoursesIdRoute
  '/api/public/webhooks/uddoktapay': typeof ApiPublicWebhooksUddoktapayRoute
  '/admin/courses/$id/edit': typeof AuthenticatedAdminCoursesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/free-class': typeof FreeClassRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/error': typeof CheckoutErrorRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/checkout/$courseId': typeof AuthenticatedCheckoutCourseIdRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/courses/$id': typeof AuthenticatedDashboardCoursesIdRoute
  '/api/public/webhooks/uddoktapay': typeof ApiPublicWebhooksUddoktapayRoute
  '/_authenticated/admin/courses/$id/edit': typeof AuthenticatedAdminCoursesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/courses'
    | '/free-class'
    | '/admin'
    | '/dashboard'
    | '/checkout/cancelled'
    | '/checkout/error'
    | '/checkout/return'
    | '/courses/$slug'
    | '/courses/'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/orders'
    | '/admin/reviews'
    | '/checkout/$courseId'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/support'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/courses/$id'
    | '/api/public/webhooks/uddoktapay'
    | '/admin/courses/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/free-class'
    | '/checkout/cancelled'
    | '/checkout/error'
    | '/checkout/return'
    | '/courses/$slug'
    | '/courses'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/orders'
    | '/admin/reviews'
    | '/checkout/$courseId'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/support'
    | '/admin'
    | '/dashboard'
    | '/dashboard/courses/$id'
    | '/api/public/webhooks/uddoktapay'
    | '/admin/courses/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/courses'
    | '/free-class'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/checkout/cancelled'
    | '/checkout/error'
    | '/checkout/return'
    | '/courses/$slug'
    | '/courses/'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/checkout/$courseId'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/support'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/courses/$id'
    | '/api/public/webhooks/uddoktapay'
    | '/_authenticated/admin/courses/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  FreeClassRoute: typeof FreeClassRoute
  CheckoutCancelledRoute: typeof CheckoutCancelledRoute
  CheckoutErrorRoute: typeof CheckoutErrorRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicWebhooksUddoktapayRoute: typeof ApiPublicWebhooksUddoktapayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/free-class': {
      id: '/free-class'
      path: '/free-class'
      fullPath: '/free-class'
      preLoaderRoute: typeof FreeClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/error': {
      id: '/checkout/error'
      path: '/checkout/error'
      fullPath: '/checkout/error'
      preLoaderRoute: typeof CheckoutErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancelled': {
      id: '/checkout/cancelled'
      path: '/checkout/cancelled'
      fullPath: '/checkout/cancelled'
      preLoaderRoute: typeof CheckoutCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/support': {
      id: '/_authenticated/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof AuthenticatedDashboardSupportRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/checkout/$courseId': {
      id: '/_authenticated/checkout/$courseId'
      path: '/checkout/$courseId'
      fullPath: '/checkout/$courseId'
      preLoaderRoute: typeof AuthenticatedCheckoutCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/webhooks/uddoktapay': {
      id: '/api/public/webhooks/uddoktapay'
      path: '/api/public/webhooks/uddoktapay'
      fullPath: '/api/public/webhooks/uddoktapay'
      preLoaderRoute: typeof ApiPublicWebhooksUddoktapayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/courses/$id': {
      id: '/_authenticated/dashboard/courses/$id'
      path: '/courses/$id'
      fullPath: '/dashboard/courses/$id'
      preLoaderRoute: typeof AuthenticatedDashboardCoursesIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/courses/$id/edit': {
      id: '/_authenticated/admin/courses/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/courses/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
  }
}

interface AuthenticatedAdminCoursesRouteChildren {
  AuthenticatedAdminCoursesIdEditRoute: typeof AuthenticatedAdminCoursesIdEditRoute
}

const AuthenticatedAdminCoursesRouteChildren: AuthenticatedAdminCoursesRouteChildren =
  {
    AuthenticatedAdminCoursesIdEditRoute: AuthenticatedAdminCoursesIdEditRoute,
  }

const AuthenticatedAdminCoursesRouteWithChildren =
  AuthenticatedAdminCoursesRoute._addFileChildren(
    AuthenticatedAdminCoursesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRouteWithChildren
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRouteWithChildren,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardSupportRoute: typeof AuthenticatedDashboardSupportRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardCoursesIdRoute: typeof AuthenticatedDashboardCoursesIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardOrdersRoute: AuthenticatedDashboardOrdersRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardSupportRoute: AuthenticatedDashboardSupportRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardCoursesIdRoute: AuthenticatedDashboardCoursesIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedCheckoutCourseIdRoute: typeof AuthenticatedCheckoutCourseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedCheckoutCourseIdRoute: AuthenticatedCheckoutCourseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRouteWithChildren,
  FreeClassRoute: FreeClassRoute,
  CheckoutCancelledRoute: CheckoutCancelledRoute,
  CheckoutErrorRoute: CheckoutErrorRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicWebhooksUddoktapayRoute: ApiPublicWebhooksUddoktapayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
